# @package _global_

# Inherit from base model configuration
defaults:
  - _base_
  - override /cv: default # Override with project defaults

model_type: transformer

# Override model_config with transformer-specific parameters
model_config:
  input_size: 17
  d_model: 256
  nhead: 8
  num_layers: 6
  dim_feedforward: 1024
  output_size: 1
  dropout: 0.2
  attention_dropout: 0.2
  sequence_length: 60
  epochs: 10
  batch_size: 32
  learning_rate: 0.001
  weight_decay: 0.00001

# Override tuning_config with transformer-specific parameters
tuning_config:
  enable_tuning: false
  param_grid:
    d_model: [32, 64]
    nhead: [4, 8]
    num_layers: [1, 2]
    learning_rate: [0.001, 0.01]
    dropout: [0.1, 0.2]
  n_trials: 8
