version: "3.9"
services:
  api:
    build: .
    command: uvicorn trade_agent.api.main:app --host 0.0.0.0 --port 8000 --workers 1
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
