[tool.black]
line-length = 88
target-version = ['py310']
include = '\.pyi?$'
exclude = '(build|dist|\.venv|\.git)'  # exclude build artifacts, venv, git

[tool.isort]
profile = 'black'

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"
