# Ruff configuration file
line-length = 120
target-version = "py311"

[lint]
select = ["E", "F", "I", "W", "B", "C4", "UP", "ARG", "SIM", "TCH", "TID", "Q", "RUF"]
ignore = [
    "E203",  # whitespace before ':'
    "E402",  # module level import not at top of file (needed for path setup)
    "E501",  # line too long (handled by line-length)
    "F401",  # imported but unused
    "F811",  # reimported
    "F841",  # assigned but never used
    "E741",  # ambiguous variable name
    "E712",  # comparison to True should be 'if cond is True:'
    "B006",  # do not use mutable data structures for argument defaults
    "B007",  # do not assign name to loop variable
    "E265",  # block comment should start with '# '
    "F821",  # undefined name
    "B004",  # do not use *args or **kwargs in function definitions
]

fixable = ["ALL"]
unfixable = []

dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"



[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
