# PPO algorithm hyperparameters (minimal for smoke test)
ppo:
  learning_rate: 0.0003
  batch_size: 64
  gamma: 0.99
  gae_lambda: 0.95
  ent_coef: 0.0
  clip_range: 0.2
  n_steps: 128
  seed: 42
  deterministic: true
