# SAC algorithm hyperparameters (minimal for smoke test)
sac:
  learning_rate: 0.0003
  batch_size: 256
  gamma: 0.99
  tau: 0.005
  train_freq: 1
  gradient_steps: 1
  ent_coef: auto
  seed: 42
  deterministic: true
