data:
  source:
    path: data/sample_data.csv
    type: csv
  symbols:
  - AAPL
  - GOOGL
  - TSLA
training:
  batch_size: 32
  epochs: 100
  include_sentiment: true
  learning_rate: 0.001
  model_config:
    cnn_filters:
    - 64
    - 128
    cnn_kernel_sizes:
    - 3
    - 5
    dropout: 0.2
    lstm_units: 256
  prediction_horizon: 1
  sequence_length: 60
  use_attention: true
