defaults:
  - _self_

pipeline:
  ensemble_pipeline:
    method: voting # or 'stacking', 'model_ensemble'
    members:
      - model: sl_pipeline
      - model: rl_pipeline
      - model: transformer_pipeline # if you have a transformer model

    evaluation:
      metric: accuracy # or 'f1', 'rmse', etc.
      cross_val: true
      n_folds: 5

    hyperparameters:
      ensemble_size: 5
      voting_weights: uniform # or 'weighted'
