apiVersion: v1
kind: ConfigMap
metadata:
  name: trading-rl-agent-config
  labels:
    app: trading-rl-agent
data:
  config.yaml: |
    environment: production
    debug: false

    data:
      symbols: ["AAPL", "GOOGL", "MSFT", "TSLA", "AMZN"]
      start_date: "2023-01-01"
      end_date: "2024-01-01"
      timeframe: "1h"
      source: "yfinance"

    execution:
      paper_trading: true
      max_position: 0.05
      stop_loss: 0.02
      take_profit: 0.05
      update_interval: 5

    training:
      epochs: 200
      batch_size: 64
      learning_rate: 0.0005
      device: "cuda"
      workers: 4

    backtesting:
      initial_capital: 100000
      commission: 0.001
      slippage: 0.0001
