apiVersion: batch/v1
kind: Job
metadata:
  name: download-datasets-job
  labels:
    app: trade-agent
    job-type: data-download
spec:
  template:
    metadata:
      labels:
        app: trade-agent
        job-type: data-download
    spec:
      restartPolicy: Never
      containers:
        - name: trading-agent
          image: trade-agent:latest
          command: ["trade-agent"]
          args:
            - "data"
            - "all"
            - "--config"
            - "/app/config/config.yaml"
            - "--verbose"
          env:
            - name: TRADING_RL_AGENT_ALPACA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: trade-agent-secrets
                  key: alpaca-api-key
            - name: TRADING_RL_AGENT_ALPACA_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: trade-agent-secrets
                  key: alpaca-secret-key
            - name: TRADING_RL_AGENT_ALPACA_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: trade-agent-secrets
                  key: alpaca-base-url
            - name: TRADING_RL_AGENT_ALPHAVANTAGE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: trade-agent-secrets
                  key: alphavantage-api-key
            - name: TRADING_RL_AGENT_NEWSAPI_KEY
              valueFrom:
                secretKeyRef:
                  name: trade-agent-secrets
                  key: newsapi-key
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
              readOnly: true
            - name: data-volume
              mountPath: /app/data
            - name: logs-volume
              mountPath: /app/logs
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "1000m"
      volumes:
        - name: config-volume
          configMap:
            name: trade-agent-config
        - name: data-volume
          persistentVolumeClaim:
            claimName: trade-agent-data
        - name: logs-volume
          persistentVolumeClaim:
            claimName: trade-agent-logs
  backoffLimit: 3
  activeDeadlineSeconds: 3600 # 1 hour timeout
