# Persistent Volume Claims for Trading RL Agent
# Note: These are examples - adjust storage class and size based on your cluster

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trade-agent-data
  namespace: trading-system
  labels:
    app: trade-agent
    volume-type: data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: standard # Adjust based on your cluster

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trade-agent-models
  namespace: trading-system
  labels:
    app: trade-agent
    volume-type: models
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard # Adjust based on your cluster

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trade-agent-artifacts
  namespace: trading-system
  labels:
    app: trade-agent
    volume-type: artifacts
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard # Adjust based on your cluster

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trade-agent-results
  namespace: trading-system
  labels:
    app: trade-agent
    volume-type: results
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard # Adjust based on your cluster

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trade-agent-logs
  namespace: trading-system
  labels:
    app: trade-agent
    volume-type: logs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard # Adjust based on your cluster

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trade-agent-mlruns
  namespace: trading-system
  labels:
    app: trade-agent
    volume-type: mlruns
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard # Adjust based on your cluster

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trading-db-data
  namespace: trading-system
  labels:
    app: trading-db
    volume-type: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trading-redis-data
  namespace: trading-system
  labels:
    app: trading-redis
    volume-type: cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trading-rabbitmq-data
  namespace: trading-system
  labels:
    app: trading-rabbitmq
    volume-type: queue
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trading-monitoring-data
  namespace: trading-system
  labels:
    app: trading-monitoring
    volume-type: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard
