apiVersion: batch/v1
kind: Job
metadata:
  name: training-job
  labels:
    app: trading-rl-agent
    job-type: training
spec:
  template:
    metadata:
      labels:
        app: trading-rl-agent
        job-type: training
    spec:
      restartPolicy: Never
      containers:
        - name: trading-agent
          image: trading-rl-agent:latest
          command: ["trading-rl-agent"]
          args:
            - "train"
            - "cnn-lstm"
            - "--config"
            - "/app/config/config.yaml"
            - "--epochs"
            - "200"
            - "--batch-size"
            - "64"
            - "--learning-rate"
            - "0.0005"
            - "--output"
            - "/app/models/cnn_lstm/"
            - "--verbose"
          env:
            - name: TRADING_RL_AGENT_ALPACA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: trading-rl-agent-secrets
                  key: alpaca-api-key
            - name: TRADING_RL_AGENT_ALPACA_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: trading-rl-agent-secrets
                  key: alpaca-secret-key
            - name: TRADING_RL_AGENT_ALPACA_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: trading-rl-agent-secrets
                  key: alpaca-base-url
            # GPU support for training
            - name: NVIDIA_VISIBLE_DEVICES
              value: "all"
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: "compute,utility"
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
              readOnly: true
            - name: data-volume
              mountPath: /app/data
              readOnly: true
            - name: models-volume
              mountPath: /app/models
            - name: artifacts-volume
              mountPath: /app/artifacts
            - name: logs-volume
              mountPath: /app/logs
            - name: mlruns-volume
              mountPath: /app/mlruns
          resources:
            requests:
              memory: "8Gi"
              cpu: "2000m"
              nvidia.com/gpu: 1
            limits:
              memory: "16Gi"
              cpu: "4000m"
              nvidia.com/gpu: 1
      volumes:
        - name: config-volume
          configMap:
            name: trading-rl-agent-config
        - name: data-volume
          persistentVolumeClaim:
            claimName: trading-rl-agent-data
        - name: models-volume
          persistentVolumeClaim:
            claimName: trading-rl-agent-models
        - name: artifacts-volume
          persistentVolumeClaim:
            claimName: trading-rl-agent-artifacts
        - name: logs-volume
          persistentVolumeClaim:
            claimName: trading-rl-agent-logs
        - name: mlruns-volume
          persistentVolumeClaim:
            claimName: trading-rl-agent-mlruns
  backoffLimit: 1
  activeDeadlineSeconds: 14400 # 4 hours timeout
