# Base Hydra config for supervised model training

defaults:
  - model: ridge # choose model group file in conf/model/
  - _self_

# Data settings
train:
  data_path: data/sample_data.csv
  target: close

# Cross-validation defaults (can be overridden per model)
cv:
  n_splits: 5
  gap: 10

# General settings
random_state: 42
output_dir: models
save_model: true

# Tuning toggles (legacy grid tuner in code; Optuna via plugin if multirun)
tuning:
  enable: false
  n_trials: 20
  scoring_metric: neg_mean_squared_error

# Optuna sweeper specific overrides (used only when -m and hydra/sweeper=optuna)
optuna:
  direction: minimize
  n_trials: 30
  n_jobs: 1
  storage: null # e.g. sqlite:///optuna.db
  study_name: sl_models
