# Enhanced configuration for unified experimentation framework
defaults:
  - model: ridge
  - _self_

# Experiment configuration
experiment:
  name: "default_experiment"

# Data configuration
train:
  data_path: "data/sample_data.parquet"
  target: "mu_hat"

data_split:
  train_ratio: 0.6
  val_ratio: 0.2
  test_ratio: 0.2

# Cross-validation configuration
cv:
  n_splits: 5
  gap: 0

cv_strategy: "purged_time_series"
cv_embargo_days: 1
cv_purge_days: 0

# Hyperparameter optimization configuration
optimization:
  enabled: false
  n_trials: 100
  metric: "sharpe"

# Ensemble configuration
ensemble:
  enabled: false
  method: "weighted_average"
  weights: {}
  gating_features: []

# Global settings
random_state: 42
output_dir: "experiments"
save_model: true

# Legacy compatibility
model_type: ${model.model_type}

hydra:
  job:
    chdir: false
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
