# CNN-LSTM Model Configuration

# CNN layer configuration
cnn_filters: [32, 64, 128]
cnn_kernel_sizes: [3, 3, 3]

# LSTM configuration
lstm_units: 128
lstm_num_layers: 2
lstm_dropout: 0.2

# General configuration
dropout: 0.5
batch_size: 32
learning_rate: 0.001

# Training configuration
epochs: 100
early_stopping_patience: 10
validation_split: 0.2

# Model architecture options
use_attention: false
use_residual: false
layer_norm: false
batch_norm: false
