# @package _global_

# Inherit from base model configuration
defaults:
  - _base_
  - override /cv: default # Override with project defaults

model_type: mlp

# Override model_config with MLP-specific parameters
model_config:
  input_size: 17
  hidden_sizes: [64, 32, 16]
  output_size: 1
  dropout: 0.2
  epochs: 10
  batch_size: 32
  learning_rate: 0.001
  weight_decay: 0.00001

# Override tuning_config with MLP-specific parameters
tuning_config:
  enable_tuning: false
  param_grid:
    hidden_sizes:
      - [64, 32]
      - [128, 64, 32]
      - [64, 32, 16]
    learning_rate: [0.001, 0.01]
    dropout: [0.1, 0.2, 0.3]
  n_trials: 10
