# Configure Hydra to use Optuna sweeper
_target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper

# Values pulled from main config via interpolation where possible
storage: ${optuna.storage}
study_name: ${optuna.study_name}
direction: ${optuna.direction}

n_trials: ${optuna.n_trials}
n_jobs: ${optuna.n_jobs}

sampler:
  _target_: optuna.samplers.TPESampler
  seed: ${random_state}

# Each parameter search space defined below will correspond to overrides.
# Note: We'll populate this at runtime via CLI overrides for flexibility.
search_space: {}
