# Trading RL Agent - Local Development Configuration
# This configuration is designed for development machines with paper trading

# ============================================================================
# ENVIRONMENT SETTINGS (REQUIRED)
# ============================================================================
environment: development # REQUIRED: development, staging, production
debug: true # REQUIRED: Enable debug mode for development

# ============================================================================
# DATA CONFIGURATION
# ============================================================================
data:
  # Data sources (REQUIRED)
  primary_source: yfinance # REQUIRED: Primary data source (yfinance, alpaca, alphavantage)
  backup_source: yfinance # REQUIRED: Backup data source for redundancy
  real_time_enabled: false # Enable real-time data feeds (disabled for dev)
  update_frequency: 60 # Data update frequency in seconds

  # Data collection (REQUIRED)
  symbols: # REQUIRED: List of trading symbols to collect
    - AAPL
    - GOOGL
    - MSFT
    - TSLA
    - AMZN
  start_date: "2023-01-01" # REQUIRED: Start date for historical data
  end_date: "2024-01-01" # REQUIRED: End date for historical data
  timeframe: "1d" # REQUIRED: Data timeframe (1d, 1h, 5m, 1m)

  # Feature engineering
  feature_window: 50 # Window size for feature calculation
  technical_indicators: true # Enable technical indicators
  sentiment_features: true # Enable sentiment analysis features

  # Storage paths
  data_path: "data/" # REQUIRED: Data storage directory
  cache_dir: "data/cache" # REQUIRED: Cache directory
  cache_ttl_hours: 24 # Cache time-to-live in hours

# ============================================================================
# MODEL CONFIGURATION
# ============================================================================
model:
  # Model type (REQUIRED)
  type: cnn_lstm # REQUIRED: Model type (cnn_lstm, rl, hybrid)
  algorithm: sac # REQUIRED: RL algorithm (ppo, sac, td3)

  # CNN+LSTM architecture
  cnn_filters: [64, 128, 256] # CNN filter sizes
  cnn_kernel_sizes: [3, 3, 3] # CNN kernel sizes
  cnn_dropout: 0.2 # CNN dropout rate (0.0-1.0)
  lstm_units: 128 # Number of LSTM units
  lstm_layers: 2 # Number of LSTM layers
  lstm_dropout: 0.2 # LSTM dropout rate (0.0-1.0)
  dense_units: [64, 32] # Dense layer units

  # Training parameters (REQUIRED)
  batch_size: 32 # REQUIRED: Training batch size
  learning_rate: 0.001 # REQUIRED: Learning rate
  epochs: 100 # REQUIRED: Number of training epochs
  total_timesteps: 1000000 # REQUIRED: Total RL training timesteps

  # Model persistence (REQUIRED)
  model_save_path: "models/" # REQUIRED: Model save directory
  checkpoint_dir: "models/checkpoints" # REQUIRED: Checkpoint directory

  # Device configuration
  device: "auto" # Device selection (auto, cpu, cuda)

# ============================================================================
# AGENT CONFIGURATION
# ============================================================================
agent:
  agent_type: sac # REQUIRED: Agent type (sac, ppo, td3)
  ensemble_size: 1 # Number of agents in ensemble
  eval_frequency: 10000 # Evaluation frequency in timesteps
  save_frequency: 50000 # Model save frequency in timesteps

# ============================================================================
# RISK MANAGEMENT CONFIGURATION
# ============================================================================
risk:
  max_position_size: 0.1 # REQUIRED: Maximum position size (0.0-1.0)
  max_leverage: 1.0 # REQUIRED: Maximum leverage
  max_drawdown: 0.15 # REQUIRED: Maximum drawdown (0.0-1.0)
  var_confidence_level: 0.05 # REQUIRED: VaR confidence level (0.0-1.0)
  stop_loss_pct: 0.02 # REQUIRED: Stop loss percentage (0.0-1.0)
  take_profit_pct: 0.05 # REQUIRED: Take profit percentage (0.0-1.0)

# ============================================================================
# EXECUTION CONFIGURATION
# ============================================================================
execution:
  broker: alpaca # REQUIRED: Trading broker (alpaca, ib, paper)
  paper_trading: true # REQUIRED: Enable paper trading for development
  order_timeout: 60 # REQUIRED: Order timeout in seconds
  max_slippage: 0.001 # REQUIRED: Maximum slippage (0.0-1.0)
  commission_rate: 0.001 # REQUIRED: Commission rate (0.0-1.0)
  execution_frequency: 5 # REQUIRED: Execution frequency in seconds
  market_hours_only: true # REQUIRED: Trade only during market hours

# ============================================================================
# MONITORING CONFIGURATION
# ============================================================================
monitoring:
  log_level: "INFO" # REQUIRED: Log level (DEBUG, INFO, WARNING, ERROR)
  log_file: "logs/trading_system.log" # REQUIRED: Log file path
  structured_logging: true # Enable structured logging
  mlflow_enabled: true # Enable MLflow tracking
  tensorboard_enabled: true # Enable TensorBoard logging
  metrics_frequency: 300 # REQUIRED: Metrics collection frequency in seconds
  alerts_enabled: true # Enable system alerts

# ============================================================================
# INFRASTRUCTURE CONFIGURATION
# ============================================================================
infrastructure:
  distributed: false # Enable distributed computing
  num_workers: 4 # REQUIRED: Number of worker processes
  gpu_enabled: true # Enable GPU support
  ray_address: null # Ray cluster address (null for local)
  use_gpu: false # Use GPU for training (false for CPU-only dev)
  max_workers: 4 # REQUIRED: Maximum number of workers
  memory_limit: "8GB" # REQUIRED: Memory limit per worker

# ============================================================================
# API KEYS AND SECRETS
# ============================================================================
# NOTE: These should be loaded from environment variables or .env file
# DO NOT hardcode API keys in configuration files
#
# Required environment variables for this configuration:
# - TRADING_RL_AGENT_ALPACA_API_KEY: Alpaca API key
# - TRADING_RL_AGENT_ALPACA_SECRET_KEY: Alpaca secret key
# - TRADING_RL_AGENT_ALPACA_BASE_URL: Alpaca base URL (optional)
# - TRADING_RL_AGENT_ALPHAVANTAGE_API_KEY: Alpha Vantage API key (optional)
# - TRADING_RL_AGENT_NEWSAPI_KEY: News API key (optional)
# - TRADING_RL_AGENT_SOCIAL_API_KEY: Social media API key (optional)

# Example .env file content:
# ALPACA_API_KEY=your_alpaca_api_key_here
# ALPACA_SECRET_KEY=your_alpaca_secret_key_here
# ALPACA_BASE_URL=https://paper-api.alpaca.markets
# ALPHAVANTAGE_API_KEY=your_alphavantage_key_here
# NEWSAPI_KEY=your_newsapi_key_here
