# Training loop settings

# Training loop settings (dict node)
training:
  total_timesteps: 1000 # lowered for fast smoke tests
  eval_freq: 10000
  checkpoint_freq: 50000
  save_best: true
  normalize_obs: true
  normalize_reward: true
