apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  service.slack: |
    token: $slack-token
  service.webhook: |
    url: $webhook-url
  template.app-sync-succeeded: |
    message: |
      Application {{.app.metadata.name}} sync succeeded.
      Environment: {{.app.metadata.labels.environment}}
      Repository: {{.app.spec.source.repoURL}}
      Revision: {{.app.status.sync.revision}}
    slack:
      attachments: |
        [{
          "title": "{{.app.metadata.name}}",
          "title_link": "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
          "color": "good",
          "fields": [{
            "title": "Sync Status",
            "value": "Succeeded",
            "short": true
          }, {
            "title": "Environment",
            "value": "{{.app.metadata.labels.environment}}",
            "short": true
          }, {
            "title": "Repository",
            "value": "{{.app.spec.source.repoURL}}",
            "short": true
          }, {
            "title": "Revision",
            "value": "{{.app.status.sync.revision}}",
            "short": true
          }]
        }]
  template.app-sync-failed: |
    message: |
      Application {{.app.metadata.name}} sync failed.
      Environment: {{.app.metadata.labels.environment}}
      Error: {{.app.status.operationState.message}}
    slack:
      attachments: |
        [{
          "title": "{{.app.metadata.name}}",
          "title_link": "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
          "color": "danger",
          "fields": [{
            "title": "Sync Status",
            "value": "Failed",
            "short": true
          }, {
            "title": "Environment",
            "value": "{{.app.metadata.labels.environment}}",
            "short": true
          }, {
            "title": "Error",
            "value": "{{.app.status.operationState.message}}",
            "short": false
          }]
        }]
  template.app-health-degraded: |
    message: |
      Application {{.app.metadata.name}} health is degraded.
      Environment: {{.app.metadata.labels.environment}}
      Health Status: {{.app.status.health.status}}
    slack:
      attachments: |
        [{
          "title": "{{.app.metadata.name}}",
          "title_link": "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
          "color": "warning",
          "fields": [{
            "title": "Health Status",
            "value": "{{.app.status.health.status}}",
            "short": true
          }, {
            "title": "Environment",
            "value": "{{.app.metadata.labels.environment}}",
            "short": true
          }]
        }]
  template.app-health-progressing: |
    message: |
      Application {{.app.metadata.name}} is progressing.
      Environment: {{.app.metadata.labels.environment}}
      Health Status: {{.app.status.health.status}}
    slack:
      attachments: |
        [{
          "title": "{{.app.metadata.name}}",
          "title_link": "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
          "color": "warning",
          "fields": [{
            "title": "Health Status",
            "value": "{{.app.status.health.status}}",
            "short": true
          }, {
            "title": "Environment",
            "value": "{{.app.metadata.labels.environment}}",
            "short": true
          }]
        }]
  template.trading-system-deployment: |
    message: |
      Trading System Deployment Event
      Application: {{.app.metadata.name}}
      Environment: {{.app.metadata.labels.environment}}
      Component: {{.app.metadata.labels.component}}
      Status: {{.app.status.sync.status}}
    slack:
      attachments: |
        [{
          "title": "Trading System Deployment",
          "title_link": "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
          "color": "{{if eq .app.status.sync.status \"Synced\"}}good{{else if eq .app.status.sync.status \"OutOfSync\"}}warning{{else}}danger{{end}}",
          "fields": [{
            "title": "Application",
            "value": "{{.app.metadata.name}}",
            "short": true
          }, {
            "title": "Environment",
            "value": "{{.app.metadata.labels.environment}}",
            "short": true
          }, {
            "title": "Component",
            "value": "{{.app.metadata.labels.component}}",
            "short": true
          }, {
            "title": "Sync Status",
            "value": "{{.app.status.sync.status}}",
            "short": true
          }]
        }]
  triggers:
    - name: on-sync-succeeded
      condition: app.status.operationState.phase in ['Succeeded']
      template: app-sync-succeeded
    - name: on-sync-failed
      condition: app.status.operationState.phase in ['Error', 'Failed']
      template: app-sync-failed
    - name: on-health-degraded
      condition: app.status.health.status == 'Degraded'
      template: app-health-degraded
    - name: on-health-progressing
      condition: app.status.health.status == 'Progressing'
      template: app-health-progressing
    - name: on-trading-system-deployment
      condition: app.metadata.labels.app == 'trading-system'
      template: trading-system-deployment
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
type: Opaque
stringData:
  slack-token: "xoxb-your-slack-bot-token"
  webhook-url: "https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-notifications
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yourusername/trading-rl-agent.git
    targetRevision: main
    path: k8s/argocd
    directory:
      recurse: true
      include: "notifications.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: ""
      kind: Secret
      jsonPointers:
        - /data
