# Example Optuna search space overrides specific to SAC (used with -m)

defaults:
  - override hydra/sweeper: optuna
  - _self_

hydra:
  sweeper:
    sampler: tpe
    direction: maximize
    n_trials: 40
    n_jobs: 1
    study_name: sac_study

sac:
  learning_rate: interval(1e-5, 5e-4)
  batch_size: choice(128, 256, 512)
  tau: interval(0.001, 0.02)
  gamma: interval(0.95, 0.999)
  ent_coef: choice('auto','auto_0.1','auto_0.5')
