# Hydra root config for RL training (PPO/SAC)

defaults:
  - algo: ppo # choose algorithm (ppo|sac)
  - features: mlp # choose feature MLP head
  - training: default
  - _self_

# Global experiment settings
experiment:
  name: rl_experiment

# Output directories
paths:
  models: models/rl
  reports: reports
  logs: logs/rl

seed: 42

device: auto # cpu|cuda|auto

env:
  data_path: data/features.parquet
  window_size: 30
  validation_split: 0.2
  initial_capital: 100000.0
  transaction_cost: 0.001

optimization:
  enabled: false # enable Optuna sweeper via -m hydra/sweeper=optuna rl_optuna
  n_trials: 20
  direction: maximize
  metric: sharpe
