# Optuna sweeper configuration for RL (used with -m hydra/sweeper=optuna rl_optuna)
# Example: python scripts/train_rl_hydra.py -m hydra/sweeper=optuna rl_optuna \
#              ppo.learning_rate=loguniform(1e-5,1e-3) ppo.batch_size=choice(32,64,128)

defaults:
  - override hydra/sweeper: optuna
  - _self_

hydra:
  sweeper:
    sampler: tpe
    direction: maximize
    n_trials: 30
    n_jobs: 1
    storage: null
    study_name: rl_study

# Provide default search space (can be overridden CLI)
ppo:
  learning_rate: interval(1e-5, 1e-3)
  batch_size: choice(32, 64, 128)
  ent_coef: interval(0.0, 0.1)
